spring:
    profiles: 
        active:
        - dev 
---
server:
    port: 8001 
spring:
    profiles: dev
    application:
        name: microservicecloud-config-dept-client
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource #当前数据源操作类型
        driver-class-name: org.gjt.mm.mysql.Driver   #mysql驱动包
        url: jdbc:mysql://localhost:3306/cloudDB01   #数据库名称
        username: root
        password: root
        dbcp2:
            min-idle: 10                                #数据库连接池的最小链接维持数
            initial-size: 10                            #初始化连接数
            max-total: 60                               #最大连接数
            max-wait-millis: 2000                       #等待连接获取的最大超时时间
mybatis:
    config-location: classpath:mybatis/mybatis.cfg.xml #mybatis配置文件所在的路径
    type-aliases-package: com.atguigu.springcloud.entities #所有Entity别名类所在包
    mapper-locations:
    - classpath:mybatis/mapper/**/*.xml  #mapper映射文件
eureka:
    client: 
        service-url:
            defaultZone: http://eureka7001.com:7001/eureka 
    instance:
        instance-id: dept-8001.com   #自定义服务名称信息
        prefer-ip-address: true   #访问路径可以显示IP地址

info: #在eureka的链接中，展示自己项目的详细信息
    app.name: atguigu-microservicecloud
    company.name: www.atguigu.com
    build.artifactId: ${project.artifactId}
    build.version: ${project.version}

#Mybatis 打印sql语句
logging:
    level:
        com:
            atguigu:
                springcloud:
                    dao: debug
---
server:
    port: 8001  
spring:
    profiles: test
    application:
        name: microservicecloud-config-dept-client
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource #当前数据源操作类型
        driver-class-name: org.gjt.mm.mysql.Driver   #mysql驱动包
        url: jdbc:mysql://localhost:3306/cloudDB02   #数据库名称
        username: root
        password: root
        dbcp2:
            min-idle: 10                                #数据库连接池的最小链接维持数
            initial-size: 10                            #初始化连接数
            max-total: 60                               #最大连接数
            max-wait-millis: 2000                       #等待连接获取的最大超时时间
mybatis:
    config-location: classpath:mybatis/mybatis.cfg.xml #mybatis配置文件所在的路径
    type-aliases-package: com.atguigu.springcloud.entities #所有Entity别名类所在包
    mapper-locations:
    - classpath:mybatis/mapper/**/*.xml  #mapper映射文件
eureka:
    client: 
        service-url:
            defaultZone: http://eureka7001.com:7001/eureka 
    instance:
        instance-id: dept-8001.com   #自定义服务名称信息
        prefer-ip-address: true   #访问路径可以显示IP地址

info: #在eureka的链接中，展示自己项目的详细信息
    app.name: atguigu-microservicecloud
    company.name: www.atguigu.com
    build.artifactId: ${project.artifactId}
    build.version: ${project.version}

#Mybatis 打印sql语句
logging:
    level:
        com:
            atguigu:
                springcloud:
                    dao: debug
        